package com.neobuk.app.ui.screens.products

import androidx.compose.foundation.background
import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Add
import androidx.compose.material.icons.filled.Close
import androidx.compose.material.icons.filled.CloudUpload
import androidx.compose.material.icons.filled.QrCode
import androidx.compose.material.icons.outlined.Image
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.scale
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.draw.clip
import androidx.compose.ui.draw.drawBehind
import androidx.compose.ui.geometry.CornerRadius
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathEffect
import androidx.compose.ui.graphics.drawscope.Stroke
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.neobuk.app.ui.theme.NeoBukCyan
import com.neobuk.app.ui.theme.Tokens
import com.neobuk.app.ui.theme.AppTextStyles
import java.util.UUID

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun AddProductSheet(
    initialBarcode: String? = null,
    onDismiss: () -> Unit,
    onSubmit: (ProductDraft) -> Unit
) {
    var productName by remember { mutableStateOf("") }
    var costPrice by remember { mutableStateOf("") }
    var sellingPrice by remember { mutableStateOf("") }
    var quantity by remember { mutableStateOf("") }
    var description by remember { mutableStateOf("") }
    var selectedUnit by remember { mutableStateOf("pcs") }
    var selectedCategory by remember { mutableStateOf("Grains") }
    var lowStockAlert by remember { mutableStateOf(true) }
    var lowStockThreshold by remember { mutableStateOf("10") }
    var batchMode by remember { mutableStateOf(false) }
    
    // Barcode State
    var barcodeGenerated by remember { mutableStateOf(initialBarcode == null) } // true if manual generation needed, false if provided
    var barcodeValue by remember { mutableStateOf(initialBarcode ?: "") }
    // If initialBarcode is provided, we treat it as "Generated/Scanned" so we show it?
    // Logic: if initialBarcode is NOT null, we should show it as if it was generated/scanned.
    // So current logic of 'barcodeGenerated' acts as "Show Generated/Scanned Visual". 
    // If we have initialBarcode, set barcodeGenerated = true.
    
    LaunchedEffect(initialBarcode) {
        if (initialBarcode != null) {
            barcodeGenerated = true
            barcodeValue = initialBarcode
        }
    }

    val scrollState = rememberScrollState()

    Column(
        modifier = Modifier
            .fillMaxWidth()
            .fillMaxHeight(0.9f) // Take up 90% of screen height
            .clip(RoundedCornerShape(topStart = 24.dp, topEnd = 24.dp))
            .background(MaterialTheme.colorScheme.surface)
            .padding(24.dp)
    ) {
        // Header
        Row(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.SpaceBetween,
            verticalAlignment = Alignment.CenterVertically
        ) {
            Column {
                Text(
                    text = "Add New Product",
                    style = AppTextStyles.pageTitle,
                    color = MaterialTheme.colorScheme.onSurface
                )
                if (batchMode) {
                    Text("Batch Mode Active", fontSize = 12.sp, color = NeoBukCyan)
                }
            }
            Row(verticalAlignment = Alignment.CenterVertically) {
               Text("Batch", fontSize = 12.sp, color = MaterialTheme.colorScheme.onSurfaceVariant)
               Switch(
                   checked = batchMode,
                   onCheckedChange = { batchMode = it },
                   modifier = Modifier.scale(0.8f)
               )
               IconButton(onClick = onDismiss) {
                   Icon(Icons.Default.Close, contentDescription = "Close")
               }
            }
        }

        HorizontalDivider(color = MaterialTheme.colorScheme.outline.copy(alpha = 0.2f), modifier = Modifier.padding(vertical = 16.dp))

        Column(
            modifier = Modifier
                .weight(1f)
                .verticalScroll(scrollState)
        ) {
            // Image Upload Placeholder
            Box(
                modifier = Modifier
                    .fillMaxWidth()
                    .height(150.dp)
                    .background(MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.3f), RoundedCornerShape(12.dp))
                    .dashedBorder(1.dp, MaterialTheme.colorScheme.outline, 12.dp),
                contentAlignment = Alignment.Center
            ) {
                Column(horizontalAlignment = Alignment.CenterHorizontally) {
                    Icon(Icons.Filled.CloudUpload, null, tint = MaterialTheme.colorScheme.onSurfaceVariant, modifier = Modifier.size(32.dp))
                    Spacer(modifier = Modifier.height(8.dp))
                    Text(
                        "Click to upload or drag and drop",
                        style = MaterialTheme.typography.bodyMedium,
                        fontWeight = FontWeight.Medium,
                        color = MaterialTheme.colorScheme.onSurface
                    )
                    Text(
                        "PNG, JPG up to 5MB",
                        style = MaterialTheme.typography.bodySmall,
                        color = MaterialTheme.colorScheme.onSurfaceVariant
                    )
                }
            }
            
            Spacer(modifier = Modifier.height(24.dp))

            // Product Name
            InputFieldLabel("Product Name")
            OutlinedTextField(
                value = productName,
                onValueChange = { productName = it },
                placeholder = { Text("Enter product name") },
                modifier = Modifier.fillMaxWidth(),
                shape = RoundedCornerShape(12.dp),
                colors = inputColors()
            )
            
            Spacer(modifier = Modifier.height(16.dp))

            // Prices Row (Cost & Selling)
            Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(16.dp)) {
                Column(modifier = Modifier.weight(1f)) {
                    InputFieldLabel("Cost Price")
                    OutlinedTextField(
                        value = costPrice,
                        onValueChange = { costPrice = it },
                        placeholder = { Text("0.00") },
                        modifier = Modifier.fillMaxWidth(),
                        shape = RoundedCornerShape(12.dp),
                        colors = inputColors(),
                        keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Number)
                    )
                }
                Column(modifier = Modifier.weight(1f)) {
                    InputFieldLabel("Selling Price")
                    OutlinedTextField(
                        value = sellingPrice,
                        onValueChange = { sellingPrice = it },
                        placeholder = { Text("0.00") },
                        modifier = Modifier.fillMaxWidth(),
                        shape = RoundedCornerShape(12.dp),
                        colors = inputColors(),
                        keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Number)
                    )
                }
            }
            
            // Profit Margin Visualization
            val cp = costPrice.toDoubleOrNull() ?: 0.0
            val sp = sellingPrice.toDoubleOrNull() ?: 0.0
            if (cp > 0 && sp > 0) {
                val profit = sp - cp
                val margin = (profit / sp) * 100
                val isProfitable = profit >= 0
                val marginColor = if (isProfitable) Color(0xFF10B981) else Color(0xFFEF4444) // Green or Red
                
                Spacer(modifier = Modifier.height(8.dp))
                Row(
                    modifier = Modifier
                        .fillMaxWidth()
                        .background(marginColor.copy(alpha = 0.1f), RoundedCornerShape(8.dp))
                        .padding(12.dp),
                    horizontalArrangement = Arrangement.SpaceBetween,
                    verticalAlignment = Alignment.CenterVertically
                ) {
                    Column {
                        Text(
                            text = if (isProfitable) "Profit Margin" else "Loss",
                            style = MaterialTheme.typography.labelMedium,
                            color = marginColor
                        )
                        Text(
                            text = "${String.format("%.0f", margin)}%",
                            style = MaterialTheme.typography.titleMedium,
                            fontWeight = FontWeight.Bold,
                            color = marginColor
                        )
                    }
                    Column(horizontalAlignment = Alignment.End) {
                         Text(
                            text = "Profit per unit",
                            style = MaterialTheme.typography.labelMedium,
                            color = marginColor
                        )
                        Text(
                            text = "KES ${String.format("%.0f", profit)}",
                            style = MaterialTheme.typography.titleMedium,
                            fontWeight = FontWeight.Bold,
                            color = marginColor
                        )
                    }
                }
            }
            
            Spacer(modifier = Modifier.height(16.dp))
            
            // Unit & Quantity Row
            Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(16.dp)) {
                Column(modifier = Modifier.weight(1f)) {
                    InputFieldLabel("Unit")
                    // Mock Dropdown
                    Box(modifier = Modifier.fillMaxWidth()) {
                        OutlinedTextField(
                            value = selectedUnit,
                            onValueChange = {},
                            readOnly = true,
                            modifier = Modifier.fillMaxWidth(),
                            shape = RoundedCornerShape(12.dp),
                            colors = inputColors(),
                            trailingIcon = { Icon(painterResource(android.R.drawable.arrow_down_float), null) }
                        )
                    }
                }
                Column(modifier = Modifier.weight(1f)) {
                    InputFieldLabel("Initial Quantity")
                    OutlinedTextField(
                        value = quantity,
                        onValueChange = { quantity = it },
                        placeholder = { Text("0") },
                        modifier = Modifier.fillMaxWidth(),
                        shape = RoundedCornerShape(12.dp),
                        colors = inputColors(),
                        keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Number)
                    )
                }
            }
            
            Spacer(modifier = Modifier.height(16.dp))
            
            // Category
            InputFieldLabel("Category")
            Box(modifier = Modifier.fillMaxWidth()) {
                OutlinedTextField(
                    value = selectedCategory,
                    onValueChange = {},
                    readOnly = true,
                    modifier = Modifier.fillMaxWidth(),
                    shape = RoundedCornerShape(12.dp),
                    colors = inputColors(),
                    trailingIcon = { Icon(painterResource(android.R.drawable.arrow_down_float), null) }
                )
            }
            
            Spacer(modifier = Modifier.height(16.dp))
            
            // Description
            InputFieldLabel("Description (Optional)")
            OutlinedTextField(
                value = description,
                onValueChange = { description = it },
                placeholder = { Text("Enter product description") },
                modifier = Modifier.fillMaxWidth().height(100.dp),
                shape = RoundedCornerShape(12.dp),
                colors = inputColors()
            )
            
            Spacer(modifier = Modifier.height(24.dp))
            
            // Barcode Section
            Card(
                colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.3f)),
                shape = RoundedCornerShape(12.dp),
                modifier = Modifier.fillMaxWidth()
            ) {
                Column(
                    modifier = Modifier.padding(16.dp),
                    horizontalAlignment = Alignment.CenterHorizontally
                ) {
                    if (!barcodeGenerated) {
                        Text("Barcode Identification", fontWeight = FontWeight.Bold, color = MaterialTheme.colorScheme.onSurface)
                        Spacer(modifier = Modifier.height(8.dp))
                        Text(
                            "Generate a unique barcode for this product to track it efficiently.",
                            style = MaterialTheme.typography.bodySmall,
                            textAlign = TextAlign.Center,
                            color = MaterialTheme.colorScheme.onSurfaceVariant
                        )
                        Spacer(modifier = Modifier.height(16.dp))
                        Button(
                            onClick = { 
                                barcodeValue = "5 012345 678900" // Mock Generation
                                barcodeGenerated = true 
                            },
                            colors = ButtonDefaults.buttonColors(containerColor = MaterialTheme.colorScheme.primary),
                            shape = RoundedCornerShape(8.dp)
                        ) {
                            Icon(Icons.Default.QrCode, null, modifier = Modifier.size(16.dp))
                            Spacer(modifier = Modifier.width(8.dp))
                            Text("Generate Barcode")
                        }
                    } else {
                        // Generated State
                        Text("Barcode Generated", fontWeight = FontWeight.Bold, color = Color(0xFF10B981))
                        Spacer(modifier = Modifier.height(12.dp))
                        // Barcode Mock Visual
                        val barcodeBarColor = MaterialTheme.colorScheme.onSurface
                        Column(
                            horizontalAlignment = Alignment.CenterHorizontally,
                            modifier = Modifier
                                .fillMaxWidth()
                                .background(MaterialTheme.colorScheme.surfaceVariant, RoundedCornerShape(8.dp))
                                .padding(16.dp)
                        ) {
                            // Realistic Barcode Drawing
                            androidx.compose.foundation.Canvas(modifier = Modifier.width(200.dp).height(80.dp)) {
                                val canvasWidth = size.width
                                val unitWidth = canvasWidth / 95f
                                
                                fun drawBar(widthModule: Int, x: Float) {
                                    drawRect(
                                        color = barcodeBarColor,
                                        topLeft = androidx.compose.ui.geometry.Offset(x, 0f),
                                        size = androidx.compose.ui.geometry.Size(widthModule * unitWidth, size.height * 0.85f)
                                    )
                                }
                                
                                var currentX = 0f
                                // Start Guard
                                drawBar(1, currentX); currentX += 2 * unitWidth
                                drawBar(1, currentX); currentX += 1 * unitWidth
                                
                                val patterns = listOf(2, 1, 3, 2, 1, 4, 3, 1, 4, 2, 2, 3)
                                patterns.forEach { width -> 
                                     currentX += 1 * unitWidth
                                     drawBar(width, currentX); currentX += width * unitWidth
                                }
                                
                                // Center
                                currentX += 1 * unitWidth
                                drawBar(1, currentX); currentX += 2 * unitWidth
                                drawBar(1, currentX); currentX += 2 * unitWidth
                                
                                patterns.reversed().forEach { width -> 
                                     drawBar(width, currentX); currentX += width * unitWidth
                                     currentX += 1 * unitWidth
                                }
                                
                                // End
                                drawBar(1, currentX); currentX += 2 * unitWidth
                                drawBar(1, currentX)
                            }
                            
                            Spacer(modifier = Modifier.height(8.dp))
                            Text(barcodeValue, fontWeight = FontWeight.Bold, fontSize = 20.sp, letterSpacing = 3.sp, color = MaterialTheme.colorScheme.onSurface)
                        }
                    }
                }
            }

            Spacer(modifier = Modifier.height(24.dp))

            // Low Stock Alert
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.SpaceBetween,
                verticalAlignment = Alignment.CenterVertically
            ) {
                Column {
                    Text("Low Stock Alert", fontWeight = FontWeight.Bold, color = MaterialTheme.colorScheme.onSurface)
                    Text("Alert when stock reaches", style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.onSurfaceVariant)
                }
                Switch(
                    checked = lowStockAlert,
                    onCheckedChange = { lowStockAlert = it },
                    colors = SwitchDefaults.colors(checkedThumbColor = Color.White, checkedTrackColor = NeoBukCyan)
                )
            }
            
            if (lowStockAlert) {
                Spacer(modifier = Modifier.height(8.dp))
                Row(verticalAlignment = Alignment.CenterVertically) {
                    OutlinedTextField(
                        value = lowStockThreshold,
                        onValueChange = { lowStockThreshold = it },
                        modifier = Modifier.width(80.dp),
                        shape = RoundedCornerShape(8.dp),
                        colors = inputColors(),
                        keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Number),
                        textStyle = LocalTextStyle.current.copy(textAlign = TextAlign.Center)
                    )
                    Spacer(modifier = Modifier.width(8.dp))
                    Text("units", color = MaterialTheme.colorScheme.onSurfaceVariant)
                }
            }
        }
        
        Spacer(modifier = Modifier.height(24.dp))

        // Submit Button
        Button(
            onClick = {
                val draft = ProductDraft(
                    name = productName,
                    costPrice = costPrice.toDoubleOrNull() ?: 0.0,
                    sellingPrice = sellingPrice.toDoubleOrNull() ?: 0.0,
                    quantity = quantity.toIntOrNull() ?: 0,
                    barcode = if (barcodeGenerated) barcodeValue else "GENERATED-${System.currentTimeMillis()}",
                    unit = selectedUnit,
                    category = selectedCategory,
                    description = description
                )
                onSubmit(draft)
                if (batchMode) {
                    // Reset fields for next entry
                    productName = ""
                    quantity = ""
                    barcodeGenerated = false
                    barcodeValue = ""
                } else {
                    onDismiss()
                }
            },
            modifier = Modifier
                .fillMaxWidth()
                .height(50.dp),
            colors = ButtonDefaults.buttonColors(containerColor = NeoBukCyan),
            shape = RoundedCornerShape(12.dp)
        ) {
            Text(
                text = if (batchMode) "Add & Continue" else "Add Product",
                fontSize = 16.sp,
                fontWeight = FontWeight.Bold,
                color = Color.White
            )
        }
    }
}

@Composable
fun InputFieldLabel(text: String) {
    Text(
        text = text,
        style = MaterialTheme.typography.bodyMedium,
        fontWeight = FontWeight.Medium,
        color = MaterialTheme.colorScheme.onSurfaceVariant,
        modifier = Modifier.padding(bottom = 6.dp)
    )
}

@Composable
fun inputColors() = OutlinedTextFieldDefaults.colors(
    unfocusedContainerColor = MaterialTheme.colorScheme.surface,
    focusedContainerColor = MaterialTheme.colorScheme.surface,
    unfocusedBorderColor = MaterialTheme.colorScheme.outline.copy(alpha = 0.5f),
    focusedBorderColor = NeoBukCyan,
    unfocusedTextColor = MaterialTheme.colorScheme.onSurface,
    focusedTextColor = MaterialTheme.colorScheme.onSurface,
    unfocusedPlaceholderColor = MaterialTheme.colorScheme.onSurfaceVariant,
    focusedPlaceholderColor = MaterialTheme.colorScheme.onSurfaceVariant
)

fun Modifier.dashedBorder(width: androidx.compose.ui.unit.Dp, color: Color, gap: androidx.compose.ui.unit.Dp) = drawBehind {
    val stroke = Stroke(
        width = width.toPx(),
        pathEffect = PathEffect.dashPathEffect(floatArrayOf(gap.toPx(), gap.toPx()), 0f)
    )
    drawRoundRect(
        color = color,
        style = stroke,
        cornerRadius = CornerRadius(12.dp.toPx())
    )
}

data class ProductDraft(
    val name: String,
    val costPrice: Double,
    val sellingPrice: Double,
    val quantity: Int,
    val barcode: String,
    val unit: String,
    val category: String,
    val description: String
)
