package com.neobuk.app.viewmodels

import androidx.compose.runtime.mutableStateListOf
import androidx.lifecycle.ViewModel
import com.neobuk.app.data.models.Task
import com.neobuk.app.data.models.TaskStatus
import java.util.Date
import androidx.lifecycle.viewModelScope
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.asStateFlow
import com.neobuk.app.data.models.Product

class TasksViewModel : ViewModel() {
    // using mutableStateListOf for easy Compose integration similar to current implementation
    private val _tasks = mutableStateListOf<Task>()
    val tasks: List<Task> get() = _tasks
    
    private val _pendingTaskCount = MutableStateFlow(0)
    val pendingTaskCount = _pendingTaskCount.asStateFlow()

    init {
        // Mock Data
        val today = Date()
        _tasks.addAll(
            listOf(
                Task(title = "Follow up unpaid invoice", dueDate = today.time, status = TaskStatus.TODO, relatedLink = "Invoice #1023"),
                Task(title = "Call supplier (Juma)", dueDate = today.time + 86400000, status = TaskStatus.IN_PROGRESS, relatedLink = "Supplier"),
                Task(title = "Pay electricity bill", dueDate = today.time - 86400000, status = TaskStatus.DONE)
            )
        )
        updateCount()
    }
    
    fun addTask(task: Task) {
        _tasks.add(0, task)
        updateCount()
    }
    
    fun updateTaskStatus(task: Task, newStatus: TaskStatus) {
        val index = _tasks.indexOf(task)
        if (index != -1) {
            _tasks[index] = _tasks[index].copy(status = newStatus)
            updateCount()
        }
    }
    
    fun updateTaskDueDate(task: Task, newDate: Long) {
        val index = _tasks.indexOf(task)
        if (index != -1) {
            _tasks[index] = _tasks[index].copy(dueDate = newDate)
            // No count update needed for date change
        }
    }

    fun removeTask(task: Task) {
        _tasks.remove(task)
        updateCount()
    }
    
    fun addAutoGeneratedTasks(products: List<Product>) {
         val lowStockItems = products.filter { it.quantity > 0 && it.quantity < 10 }
            lowStockItems.forEach { product ->
                val taskTitle = "Restock ${product.name} (${product.quantity.toInt()} units left)"
                // Avoid redundant adding
                if (_tasks.none { it.title == taskTitle }) {
                    addTask(
                        Task(
                            title = taskTitle,
                            dueDate = System.currentTimeMillis(),
                            status = TaskStatus.TODO,
                            relatedLink = "Stock Alert"
                        )
                    )
                }
            }
    }

    private fun updateCount() {
        _pendingTaskCount.value = _tasks.count { it.status == TaskStatus.TODO || it.status == TaskStatus.IN_PROGRESS }
    }
}
